version: '3.8'

services:
  spark-app:
    build:
      context: . 
      dockerfile: Dockerfile
    image: my-spark-app
    container_name: spark-app-container
    volumes:
      - ./src/app.py:/app/app.py
      - ./src/run.sh:/app/run.sh
      - ./data/steambans:/app/steambans
      - ./data/bronze:/app/data/bronze
      - ./data/silver:/app/data/silver
      - ./data/gold:/app/data/gold
      - ./logs:/app/logs
    tty: true
    stdin_open: true
    command: /app/run.sh